<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('order_payments', function (Blueprint $table) {
            $table->id();

            $table->foreignId('order_id');

            $table->string('payment_receipt')->nullable(); // File path for the payment receipt (nullable)
            $table->string('transaction_id')->unique(); // Transaction ID (required)and unique it is automatically generated by the system
            $table->date('payment_date'); // Payment date

            $table->foreign('order_id')->references('id')->on('retailor_orders')->onDelete('cascade');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('order_payments');
    }
};
